# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [215]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

print("(a)the shape:")
print(arr.shape)

print("(a)number of dimensions: ")
print(arr.ndim)

print("(a) type:")
print(type(arr))

print("(b)  the sum of elements in arr:")
print(arr.sum())

print("(c) the mean of elements in arr:")
print(arr.mean())

print("(d) the same shape as arr but filled with zeros:")
arr2 = np.zeros_like(arr)
print(arr2)

print("(e) the same shape as arr but filled with ones:")
arr1 = np.ones_like(arr)
print(arr1)

print("(f) the same shape as arr but where all elements are squared values:")
print(arr**2)

print("(g) 3*3 resulting from multiplication of arr with transpose:")
arrtt = arr.T     
arr0 = np.dot(arr, arrt)   
print(arr0)

(a)the shape:
(3, 5)
(a)number of dimensions: 
2
(a) type:
<class 'numpy.ndarray'>
(b)  the sum of elements in arr:
105
(c) the mean of elements in arr:
7.0
(d) the same shape as arr but filled with zeros:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(e) the same shape as arr but filled with ones:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(f) the same shape as arr but where all elements are squared values:
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
(g) 3*3 resulting from multiplication of arr with transpose:
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [212]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows


print("(a)the shape of the dataframe:")
print(df.shape)

print("(b) all the columns:")
all_column = list(df.head(0))
print(all_column)

print("(c)the 3rd element: ")
print(df.iloc[2])

print("(d) the average of 'petal_width' where species is 'virginica':")
print(df.groupby('species').mean().iloc[2,3])


print("(e)the maximum of 'sepal_width' where species is 'setosa':")
print(df.groupby('species').max().iloc[0,1])


print("(f) the average value of sepal_length:")
print(df.mean()['sepal_length'])


print("(g) the maximum value of sepal_width:")
print(max_series['sepal_width'])

print("(h)the minimum value of petal_width")
print(df.min()['petal_width'])
      

(a)the shape of the dataframe:
(150, 5)
(b) all the columns:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
(c)the 3rd element: 
sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object
(d) the average of 'petal_width' where species is 'virginica':
2.026
(e)the maximum of 'sepal_width' where species is 'setosa':
4.4
(f) the average value of sepal_length:
5.843333333333335
(g) the maximum value of sepal_width:
4.4
(h)the minimum value of petal_width
0.1


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)
