# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [1]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [120]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

# (a)
row, column = arr.shape
print ("(a) Shape of the array: ", arr.shape, "(Dimensions:", row, "rows,", column, "columns)") 

# (b)
print ("(b) Sum of elements: ", arr.sum())

# (c)
print ("(c) Mean of elements: ", arr.mean())

#( d)
zeros = np.zeros((3,5)) #a 2d array with 3 rows and 5 columns
print ("(d) Array filled with zeros: ",'\n',zeros)

# (e)
## the array can be created by numpy function
ones_1 = np.ones((3,5)) 
## Or use a for loop 
ones_2 = []
for i in range(15):
        ones_2.append(1.0)
ones_2 = np.array(ones_2).reshape(3,5)
print ("(e) Array filled with ones: ",'\n',ones_2) 

# (f)
## the type of array accepts the basic math functions, such as add, subtract, multiply, and divide
sqr = arr **2 
print ("(f) Array filled with squared values: ",'\n',sqr)

# (g)
matrix = np.dot(arr, arr.T)
print ("(g) New matrix: ",'\n',matrix) #multiply the 3x5 matrix and 5x3 matrix

(a) Shape of the array:  (3, 5) (Dimensions: 3 rows, 5 columns)
(b) Sum of elements:  105
(c) Mean of elements:  7.0
(d) Array filled with zeros:  
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(e) Array filled with ones:  
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(f) Array filled with squared values:  
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
(g) New matrix:  
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

# (a) Determine the shape of the dataframe
print ("(a) Shape: ", df.shape)

# (b) Print out all the columns of the dataframe
print ("(b) Columns: ",df.columns.values)

# (c) Print the 3rd element of the dataframe
## 3rd column
## both of .iloc and .loc can take a single element from the dataframe
third_column_1 = df.iloc[:, 2] #by locations
third_column_2 = df.loc[:, 'petal_length'] #by labels

print ("(c) 3rd element (first 5 rows only): ",'\n', third_column_2.head())

# (d) Find the average of 'petal_width' where species is 'virginica'
## use groupby to calculate the mean values for each type of iris
## take out the target output by filtering the row and column name

print ("(d) Average of petal width for virginica iris: %.4f" 
       % df.groupby('species').mean().loc['virginica','petal_width']) 

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
## the thinking process is same with part (d)

print ("(e) Maximum of sepal width for setosa iris: %.2f" 
       % df.groupby('species').max().loc['setosa','sepal_width']) 

# (f): What is the average value of sepal_length
## a single column can be called by name directly

print ("(f) Average value of sepal length: %.4f" 
       % df['sepal_length'].mean()) 

# (g): What is the maximum value of sepal_width
## same thinking process as (f), but .loc can do the same thing

print ("(g) Maximum value of sepal width: %.4f" 
       % df.loc[:, 'sepal_width'].max()) 

# (h): What is the minimum value of petal_width
## same thinking process as (f) and (g), but accomplished by .iloc

print ("(g) Minimum value of petal width: %.4f" 
       % df.iloc[:, 3].min()) 




(a) Shape:  (150, 5)
(b) Columns:  ['sepal_length' 'sepal_width' 'petal_length' 'petal_width' 'species']
(c) 3rd element (first 5 rows only):  
 0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: petal_length, dtype: float64
(d) Average of petal width for virginica iris: 2.0260
(e) Maximum of sepal width for setosa iris: 4.40
(f) Average value of sepal length: 5.8433
(g) Maximum value of sepal width: 4.4000
(g) Minimum value of petal width: 0.1000


In [123]:
df.head(10) #the famous iris dataset

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


<strong> interested datasets description and target questions

(1) House Prices dataset <br>
Description: <br> The dataset contains 79 explanatory variables that used to describe residential properties from multiple aspects. <br>
Goal: <br>Identify the significant features, then predict the final price of each property. <br>

The biggest challenge I can see for now, is how to select the key features to increase the accuracy rate.


(2) College Scorecard dataset <br>
Description: <br> The dataset described the under-graduate students' completion, debt, repayment, earnings status from 1996 to 2017. <br>
Goal: <br>
* predict the student's earning level. 
* identify the relationship between loan performance and student earning level for each school (Does higher earning means better loan performance? Any suprise?)
* identify the relationship between financial aid and college completion rate. (Will the financial aid really helps the student to finish the shool?) <p>

Due to the size of dataset, the key issue may be the data exploration and data cleaning processes.

(3) Million Song Dataset <br>
Description: <br> It is the official song tag and song similarity datateset which partnered with Last.fm. The dataset contains more than 900,000 tracks with multiply types of lyrics, and the simular songs. <br>
Goal: <br> Classify the type of lyrics. <p>
The key problem will be how to dealing with the multi-tags songs during classification.