# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [52]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5) # example 1 of what arr could be
arr = np.arange(100).reshape(10,10) # example #2 of what arr could be

print("The shape is {}, it is {} dimensions and the type is {}".format(arr.shape, arr.ndim, type(arr)))
print("The sum of elements in arr is {}".format(arr.sum()))
print("The mean of elements in arr is {}".format(arr.mean()))
print("\n")
print("An array of the same shape as arr but filled with zeros")
print(np.zeros_like(arr))
print("\n")
print("An array of the same shape as arr but filled with ones")
print(np.ones_like(arr))
print("\n")
print("An array of the same shape as arr but where all elements are squared values")
print(np.square(arr))
print("\n")
print("arr multiplied by transpose(arr)")
print(np.dot(arr,np.transpose(arr)))


The shape is (3, 5), it is 2 dimensions and the type is <class 'numpy.ndarray'>
The sum of elements in arr is 105
The mean of elements in arr is 7.0


An array of the same shape as arr but filled with zeros
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


An array of the same shape as arr but filled with ones
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


An array of the same shape as arr but where all elements are squared values
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


arr multiplied by transpose(arr)
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [54]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows
print("The shape of the dataframe is", df.shape)
print("\n")
print("The columns of the dataframe are", df.columns)
print("\n")
print("The 3rd element of the dataframe is", df.iloc[2])
print("\n")
print("The average of petal_width where species is virginica is", 
      df[df["species"] == 'virginica']['petal_width'].mean())
print("\n")
print("The maximum of sepal_width where species is setosa is", 
     df[df["species"] == 'setosa']['sepal_width'].max())
print("\n")
print("The average value of sepal_length is", df["sepal_length"].mean())
print("\n")
print("The average value of sepal_width is", df["sepal_width"].max())
print("\n")
print("The average value of petal_width is", df["petal_width"].min())

The shape of the dataframe is (150, 5)


The columns of the dataframe are Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


The 3rd element of the dataframe is sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


The average of petal_width where species is virginica is 2.026


The maximum of sepal_width where species is setosa is 4.4


The average value of sepal_length is 5.843333333333335


The average value of sepal_width is 4.4


The average value of petal_width is 0.1


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)
