# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [14]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [4]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an ar
ray result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot


SyntaxError: invalid syntax (<ipython-input-4-6a235e34f363>, line 10)

In [15]:
import numpy as np
arr = np.arange(15).reshape(3, 5)
shape = arr.shape
dim = arr.ndim
type(arr)
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print("Shape of this array is: ", arr.shape)

# (b) Determine the sum of elements in arr
print("Number of dimension is: ", arr.ndim)

# (c) Determine the mean of elements in arr
print("The mean of values in arr is: ", arr.mean)

# (d) Create an array of the same shape as arr but filled with zeros
print(np.zeros_like(arr))

# (e) Create an array of the same shape as arr but filled with ones
print(np.ones_like(arr))

# (f) Create an array of the same shape as arr but where all elements are squared values
print(np.square(arr))

# (g) Create an ar
arrt=arr.T
print(np.dot(arr,arrt))

Shape of this array is:  (3, 5)
Number of dimension is:  2
The mean of values in arr is:  <built-in method mean of numpy.ndarray object at 0x107f48760>
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [36]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

# (a) Determine the shape of the dataframe
print(df.shape)

# (b) Print out all the columns of the dataframe
column = list(df.head(0))
print(column)

# (c) Print the 3rd element of the dataframe
print(df.iloc[2],)

# (d) Find the average of 'petal_width' where species is 'virginica'
vmean = df.groupby("species").mean().iloc[2,3]
print(vmean)

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
df.groupby("species").max()
smax = df.groupby("species").max().iloc[0,1]
print(smax)

# (f): What is the average value of sepal_length
df["sepal_length"].mean()
print(df['sepal_length'].mean())


# (g): What is the maximum value of sepal_width
df["sepal_width"].max()
print(df["sepal_width"].max())

# (h): What is the minimum value of petal_width
df["petal_width"].min()
print(df["petal_width"].min())



(150, 5)
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object
2.026
4.4
5.843333333333335
4.4
0.1


## GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)

#1 CRIME INCIDENT REPORTS
Crime incident reports are provided by Boston Police Department (BPD) to document the initial details surrounding an incident to which BPD officers respond. This is a dataset containing. This dataset counts all the crime since 2015. We can analysis the location, income difference, time or any else variables in this data to know which area need more police force and find out the reason of the inequality distribution of crime. Retrieve from: https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b

#2 Population Estimates
The program publishes estimates of the population by age, sex, race, and Hispanic origin for the nation, states, and counties. It also provides estimates of the total population for functioning governmental units. We can do research about the distribution of people among United States. Then we can analyze why differernt kind people choose differet areas to live. We also can find out the birth rate and death rate in different place and analyze the reason od those difference. Retrieve from: https://catalog.data.gov/dataset/population-estimates

#3 Inpatient Prospective Payment
The data provided here include hospital-specific charges for the more than 3,000 U.S. hospitals that receive Medicare Inpatient Prospective Payment System (IPPS) payments for the top 100 most frequently billed discharges, paid under Medicare based on a rate per discharge using the Medicare Severity Diagnosis Related Group. We can find out the medicare cost in differernt area and trying to set the proper price for patient and trying to give some suggestions to insurance policy. Retrieve from: http://www.fao.org/gender-landrights-database/resources/publications/publication-details/en/c/385329/



