# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [3]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [4]:
## arr is the value that we are going to use for our first part
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr

#shape
shape = arr.shape
print("Shape of the array is {}".format(shape))

#type of elements
type = arr.dtype
print("Array arr has elements of {} type".format(type))

#dimensions
rows, columns = arr.shape
dimensions = "Dimensions of this array. There are {} rows and {} columns".format(rows, columns)
print(dimensions)

Shape of the array is (3, 5)
Array arr has elements of int64 type
Dimensions of this array. There are 3 rows and 5 columns


In [6]:
# (b) Determine the sum of elements in arr

# Sum of elements in array
arr_sum = np.sum(arr)
print(arr_sum)

# sum of individual rows in array
arr_rows = np.sum(arr, axis=1)
print("Array containing the sum of individual rows is", arr_rows)

# sum of individual columns in array
arr_columns = np.sum(arr, axis=0)
print("Array containing the sum of individual columns is", arr_columns)


105
Array containing the sum of individual rows is [10 35 60]
Array containing the sum of individual columns is [15 18 21 24 27]


In [7]:
# (c) Determine the mean of elements in arr
arr_mean = np.mean(arr)
print(arr_mean)

7.0


In [8]:
# (d) Create an array of the same shape as arr but filled with zeros
arr_zero = np.zeros(arr.shape)
print(arr_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# (e) Create an array of the same shape as arr but filled with ones
arr_ones = np.ones(arr.shape)
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
# (f) Create an array of the same shape as arr but where all elements are squared values
arr_squared = np.square(arr)
print(arr_squared)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


In [11]:
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr_transpose = np.transpose(arr)
#print(arr_transpose)

arr_new = np.dot(arr, arr_transpose)
print(arr_new)

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [12]:
### GRADED
# The following piece of code creates a DataFrame 

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [13]:
# (a) Determine the shape of the dataframe

dataframe_shape = df.shape
print("Shape of the dataframe is {}".format(dataframe_shape))

Shape of the dataframe is (150, 5)


In [14]:
# (b) Print out all the columns of the dataframe

dataframe_col = df.columns
print("Columns in the dataframe:", list(dataframe_col))

Columns in the dataframe: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']


In [36]:
# (c) Print the 3rd element of the dataframe

df_3 = df.loc[[3],['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']]
print(df_3)

   sepal_length  sepal_width  petal_length  petal_width species
3           4.6          3.1           1.5          0.2  setosa


In [16]:
# (d) Find the average of 'petal_width' where species is 'virginica'

avg_columns = df.loc[df['species'] == 'virginica'].mean()
print("The average value of petal_width is {}".format(avg_columns['petal_width']))

The average value of petal_width is 2.0260000000000002


In [17]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'

max_relevant_cols = df.loc[df['species'] == 'setosa'].max()
print("Maximum of 'sepal_width' where species is 'setosa' is {}".format(max_relevant_cols['sepal_width']))

Maximum of 'sepal_width' where species is 'setosa' is 4.4


In [18]:
# (f): What is the average value of sepal_length

average_value = df['sepal_length'].mean()
print("The average value of sepal_length is {}".format(average_value))

The average value of sepal_length is 5.843333333333334


In [19]:
# (g): What is the maximum value of sepal_width

max_sepal_width = df['sepal_width'].max()
print("Maximum value of sepal_width {}".format(max_sepal_width))

Maximum value of sepal_width 4.4


In [20]:
# (h): What is the minimum value of petal_width

min_petal_width = df['petal_width'].min()
print("Minimum value of petal_width {}".format(min_petal_width))


Minimum value of petal_width 0.1


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


For the capstone project I have shortlisted below 3 datasets:
    
    
## Dataset 1: Employee Earnings Report 2016
    
Each year, the **City of Boston** publishes payroll data for employees from various departments with various job titles.
I have chosen the **Employee Earning Report** for year **2016**. This dataset contains `employee names`,`job details` (department and job titles), and `earnings information` including `base salary`, `overtime`, and `total compensation` for employees of the Boston City. 

### Questions that can be answered:

    1. Maximum and minimum salary for various job titles and department.
    2. Average salary for various departments/job titles.
    3. Which department requires more overtime. 
    4. Which department/job title pays more overtime salary.
    
----

## Dataset 2: Crime Data Seattle City
    
This dataset represents, crime reported to the **Seattle Police Department (SPD)** from year **1908 to 2018**. There are more than **500k** rows in this dataset. Each row contains the record of a unique event where at least one criminal offense was reported by a member of the community or detected by an officer in the field.

This dataset contains `crime occured date` and occured `time`, `reported date` and `reported time`, `type of crime` and `neighbourhood`.

### Questions that can be answered:

    1. In which neighbourhood majority of the crimes happen.
    2. At what time crimes occur the most and when the least.
    3. What type of crimes happen more in Seattle.
    
----

## Dataset 3: City of Seattle Wages: Comparison by Gender - All Job Classifications
    
This dataset represents, **average pay comparison of male and female wages** by job classification (except Library job classes) for **City of Seattle**. The data contains weighted `average hourly pay rates` for women and men and the `average of all employee wages` in the class.
    
### Questions that can be answered:

    1. Number of men and women are there for a specific job title.
    2. Comparison of the `average hourly pay rate` of men and women for a specific job title.
    3. Jobs which do not have men presence and jobs which do not have women presence.
    
    