# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [111]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [75]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print('(a)Shape',arr.shape)
print('(a)Dimensions',arr.ndim)
print('(a)Type of element',type(arr))

(a)Shape (3, 5)
(a)Dimensions 2
(a)Type of element <class 'numpy.ndarray'>


In [59]:
# (b) Determine the sum of elements in arr
print('(b)',arr.sum())
arr.sum(axis=0)
arr.sum(axis=1)

(b) 105


array([10, 35, 60])

In [117]:
# (c) Determine the mean of elements in arr
result = arr.mean()
print('(c)',result)

(c) 7.0


In [72]:
# (d) Create an array of the same shape as arr but filled with zeros
d = np.zeros((3,5))
print('(d)',d)

(d) [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [102]:
# (e) Create an array of the same shape as arr but filled with ones
e = np.ones((3,5))
print('(e)',e)

(e) [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [120]:
# (f) Create an array of the same shape as arr but where all elements are squared values
import math
np.sqrt(arr)
# print('(f)', arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [132]:
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). 
#Hint: use np.dot
g = np.dot(3,3)
print('(g)',g)

(g) 9


In [90]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [104]:
# (a) Determine the shape of the dataframe
print('(a)Shape',df.shape)

(a)Shape (150, 5)


In [84]:
# (b) Print out all the columns of the dataframe
print(('(b)'),df)

(b)      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0

In [129]:
# (c) Print the 3rd element of the dataframe
print('(c)3rd element',
      df['petal_length'])

(c)3rd element 0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
5      1.7
6      1.4
7      1.5
8      1.4
9      1.5
10     1.5
11     1.6
12     1.4
13     1.1
14     1.2
15     1.5
16     1.3
17     1.4
18     1.7
19     1.5
20     1.7
21     1.5
22     1.0
23     1.7
24     1.9
25     1.6
26     1.6
27     1.5
28     1.4
29     1.6
      ... 
120    5.7
121    4.9
122    6.7
123    4.9
124    5.7
125    6.0
126    4.8
127    4.9
128    5.6
129    5.8
130    6.1
131    6.4
132    5.6
133    5.1
134    5.6
135    6.1
136    5.6
137    5.5
138    4.8
139    5.4
140    5.6
141    5.1
142    5.1
143    5.9
144    5.7
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64


In [192]:
# (d) Find the average of 'petal_width' where species is 'virginica'
d = df.loc[df['species'] == 'virginica']
d['petal_width'].mean()

2.026

In [194]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
d = df.loc[df['species'] == 'setosa']
d['sepal_width'].max()

4.4

In [201]:
# (f): What is the average value of sepal_length
ds = df['sepal_length']
ds.mean()

5.843333333333335

In [207]:
# (g): What is the maximum value of sepal_width
df['sepal_width'].max()

4.4

In [210]:
# (h): What is the minimum value of petal_width
df['petal_width'].min()

0.1

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)
