# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [4]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
import numpy as np
arr = np.arange(15).reshape(3, 5)

shape = arr.shape
dim = arr.ndim
type(arr)
print('a. The shape of arr is:',shape, ', and number of dimentions is:', dim, '; type:',type(arr))     #(a)

sum = arr.sum()
print('b. The sum of values in arr is:', sum)     #(b)

mean = arr.mean()
print('c. The mean of values in arr is:', mean)     #(c)

arr2 = np.zeros_like(arr)     #(d)
print('d.', arr2)

arr3 = np.ones_like(arr)     #(e)
print('e.', arr3)

arr4 = np.square(arr)     #(f)
print('f.', arr4)

arrt = arr.T     #(g)
arr5 = np.dot(arr, arrt)   
print('g.', arr5)


a. The shape of arr is: (3, 5) , and number of dimentions is: 2 ; type: <class 'numpy.ndarray'>
b. The sum of values in arr is: 105
c. The mean of values in arr is: 7.0
d. [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
e. [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
f. [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
g. [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [8]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

df.shape     #(a)
print('a. The numbers of rows and columns of this dataframe are',df.shape,", respectively.")

column = list(df.head(0))     #(b)
print('b.',column)

df.iloc[2]     #(c)
print('c. The third element of the dataframe is:', df.iloc[2],'.')

df.groupby('species').mean().iloc[2,3]     #(d)
vmean = df.groupby('species').mean().iloc[2,3]
print('d. The average number of petal_width of species Virginica is:',vmean, '.')

df.groupby('species').max()     #(e)
smax = df.groupby('species').max().iloc[0,1]
print('e. The maximum number of sepal_width of species Setosa is:',smax, '.')

df['sepal_length'].mean()     #(f)
print('f. The average value of sepal_length is:', df['sepal_length'].mean(),'.')

df['sepal_width'].max()     #(g)
print('g. The maximum value of sepal_width is:',df['sepal_width'].max(),'.')

df['petal_width'].min()     #(h)
print('h. The minimum value of petal_width is:',df['petal_width'].min(),'.')

a. The numbers of rows and columns of this dataframe are (150, 5) , respectively.
b. ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
c. The third element of the dataframe is: sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object .
d. The average number of petal_width of species Virginica is: 2.026 .
e. The maximum number of sepal_width of species Setosa is: 4.4 .
f. The average value of sepal_length is: 5.843333333333334 .
g. The maximum value of sepal_width is: 4.4 .
h. The minimum value of petal_width is: 0.1 .


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


Datasets of interest: 
1. Crime Incident Rerpots (August 2015 - To Date); link:https://data.boston.gov/dataset/6220d948-eae2-4e4b-8723-2dc8e67722a3/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b/download/crime.csv 

2. BPD Firearm Recovery Counts; link: https://data.boston.gov/dataset/3937b427-6aa4-4515-b30d-c76771313feb/resource/a3d2260f-8a41-4e95-9134-d14711b0f954/download/bpdfirearmrecoveries20180419.csv

3. Big Belly Alerts 2014; link:https://data.boston.gov/dataset/fb5a108b-5f3a-4347-a091-6bc2b1753ea5/resource/c8c54c49-3097-40fc-b3f2-c9508b8d393a/download/big-belly-alerts-2014.csv

Dataset description:
The crime incident reports dataset lists information of incidents that Boston PD officers responded. Details include the description, locations and time incidents took place, whether firearms were involved, and so sorth. From this database, one could categorize crime incidents based on category, danger level, and figure out which areas are prime locations for vicious crimes such as shootings and robberies, and Boston PD could use these information to modify the dispatch and patrol approaches. 

The BPD firearm recovery counts dataset shows the methods of recovery and counts of firearms recovered by different methods. Information collected from the dataset can be used to compare the results of different firearm recovery methods and to select a better overall recovery method to recover firearms more safely and efficiently.

The big belly alerts 2014 dateset describes the locations, fullness and other useful information about trash receptacles located throughout the city of Boston. The information from this dataset can be analyzed to show trash receptacles that are full most of the time, as well as those that tend to remain low on fullness or empty frequently. The city then can use these information to relocate trash receptacles to make them work more efficiently. 