# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [3]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)


# (a)Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print("(a)\narr")
print(arr)
print("="*10)
print("arr shape")
print(arr.shape)
print("="*10)
print("arr type")
print(type(arr))
print("="*10)
print("type of elements")
print(arr.dtype)

# (b) Determine the sum of elements in arr
print("\n(b)")
print("sum of elements in arr")
print(np.sum(arr))


# (c) Determine the mean of elements in arr
print("\n(c)")
print("mean of elements in arr")
print(np.mean(arr))

# (d) Create an array of the same shape as arr but filled with zeros
print("\n(d)")
print("same shape as arr but filled with zeros")
print(np.zeros_like(arr))

# (e) Create an array of the same shape as arr but filled with ones
print("\n(e)")
print("the same shape as arr but filled with ones")
print(np.ones_like(arr))

# (f) Create an array of the same shape as arr but where all elements are squared values
print("\n(f)")
print("he same shape as arr but where all elements are squared values")
print(np.full_like(arr,1.0,dtype=np.double))

# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
print("\n(g)")
print("shape 3*3 resulting from multiplication of arr with transpose(arr)")
print(np.dot(arr,np.transpose(arr)))

(a)
arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr shape
(3, 5)
arr type
<class 'numpy.ndarray'>
type of elements
int64

(b)
sum of elements in arr
105

(c)
mean of elements in arr
7.0

(d)
same shape as arr but filled with zeros
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

(e)
the same shape as arr but filled with ones
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

(f)
he same shape as arr but where all elements are squared values
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

(g)
shape 3*3 resulting from multiplication of arr with transpose(arr)
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [4]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(df.head(10)) #prints the first 10 rows

# (a) Determine the shape of the dataframe
print("\n(a)")
print("the shape of the dataframe")
print(df.shape)

# (b) Print out all the columns of the dataframe
print("\n(b)")
print("all the columns of the dataframe")
print(df.columns)

# (c) Print the 3rd element of the dataframe
print("\n(c)")
print("the 3rd element of the dataframe")
print(df.iloc[2,])

# (d) Find the average of 'petal_width' where species is 'virginica'
print("\n(d)")
print("average of 'petal_width' where species is 'virginica'")

a=df[df['species']== 'virginica']
print(a['petal_width'].mean())


# (e) Find the maximum of 'sepal_width' where species is 'setosa'
print("\n(e)")
print("the maximum of 'sepal_width' where species is 'setosa'")
b=df[df['species']== 'setosa']
print(b['sepal_width'].max())

# (f): What is the average value of sepal_length
print("\n(f)")
print("average value of sepal_length")
print(df['sepal_length'].mean())

# (g): What is the maximum value of sepal_width
print("\n(g)")
print("the maximum value of sepal_width")
print(df['sepal_width'].max())

# (h): What is the minimum value of petal_width
print("\n(h)")
print("the minimum value of petal_width")
print(df['petal_width'].min())


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

(a)
the shape of the dataframe
(150, 5)

(b)
all the columns of the dataframe
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

(c)
the 3rd element of the dataframe
sepal_length       4.7
sepal_width        3.2
petal_length       1.3


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
  *  1. The property assessment from:https://data.boston.gov/dataset/property-assessment
  *  2. World Income Inequality Database from: https://old.datahub.io/dataset/world-income-inequality-database
       & US Household Income Statistics from: https://www.kaggle.com/goldenoakresearch/us-household-income-stats-geo-locations
  *  3. Consumer Complaint Database from: https://catalog.data.gov/dataset/consumer-complaint-database#topic=consumer_navigation
  
  
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)
    * 1. The property assessment
       * Gives property, or parcel, ownership together with value information, which ensures fair assessment of Boston taxable and non-taxable property of all types and classifications. 
       * Through analysis, we may get the information such like: which erea has the highest house price? The general information about the property assessment of Boston:the average value of the house, the mean of the size of the house, etc. What's the relationship between the value and the size? ..etc
   
  * 2. World Income Inequality Database & US Household Income Statistics
     * The database contains data on inequality in the distribution of income in various countries. The central variable in the dataset is the Gini index, a measure of income distribution in a society.(last update in 2015) For the US Household Income Statistics, it contains 32,000 records on US Household Income Statistics & Geo Locations.(last update in 2017) 
     * Through analysis, we may get the idea such like: the distribution of the income worldwide in terms of regions and countries. The development curve in the recent years for each country and states of US. What's the different distribution in different level of income group?..etc.
     
  * 3. Consumer Complaint Database
     * The dataset is published by the Consumer Financial Protection Bureau. These are complaints they have received about financial products and services ranging from 2013 to 2018.
     * Through analysis, we may get the idea such like: What is the average number of the complaints ever month? The distributions of the complaints in different states or companiies. Is there a relationship between the products of the complaints and the states or submittion way?
  