# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [14]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [222]:
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
import numpy as np
arr = np.array(
    [
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]
    ])

print("Shape")
print(arr.shape)

print("dimesnsion")
print(arr.ndim)

print("element")
print(arr.dtype)

Shape
(3, 5)
dimesnsion
2
element
int32


In [256]:
# (b) Determine the sum of elements in arr
result = np.sum(arr)
print(result)

105


In [257]:
# (c) Determine the mean of elements in arr
result = np.mean(arr)
print(result)

7.0


In [258]:
# (d) Create an array of the same shape as arr but filled with zeros
arr = np.zeros_like(arr)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [259]:
# (e) Create an array of the same shape as arr but filled with ones
a = np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [263]:
# (f) Create an array of the same shape as arr but where all elements are squared values  
print ("Square Value of arr : \n", np.square(arr))

Square Value of arr : 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


In [267]:
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot

arr_transpose = np.transpose(arr)

arr_new = np.dot(arr, arr_transpose)
print(arr_new)

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [164]:

# (a) Determine the shape of the dataframe
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
#print(df.shape)

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows



Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [237]:
# (d) Find the average of 'petal_width' where species is 'virginica'
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
average=df.loc[df['species'] == 'virginica']
average.loc[:,"petal_width"].mean()

2.026

In [206]:
# (c) Print the 3rd element of the dataframe
import pandas as pd
df.iloc[[3]]

sepal_length  sepal_width  petal_length  petal_width species
3           4.6          3.1           1.5          0.2  setosa

In [238]:
# (b) Print out all the columns of the dataframe
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [239]:
# (d) Find the average of 'petal_width' where species is 'virginica'

import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
average=df.loc[df['species'] == 'virginica']
average.loc[:,"petal_width"].mean()

2.026

In [165]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
average=df.loc[df['species'] == 'setosa']
average.loc[:,"sepal_width"].max()


4.4

In [166]:
# (f): What is the average value of sepal_length
average.loc[:,"sepal_length"].mean()

5.005999999999999

In [168]:
# (g): What is the maximum value of sepal_width
average.loc[:,"sepal_width"].max()

4.4

In [169]:
# (h): What is the minimum value of petal_width
average.loc[:,"petal_width"].min()

0.1

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


I have shortlisted 3 datasets here :

1.Employee Earning

2.Crime Incident

3.Property Assesment

#### Employee Earning Report 2017

Every year the city of Boston publishes the payroll data for employee. Dataset contain different job titles, employee names and their respective earnings information such as base salary, Overtime earning and total earning of each employee.
Questions can be answered:

1. Which are the top 5 job title by salary.
2. Salary range for different job titles by department.
3. Which are the top 10 highest salary paying cities.
4. Average salary for each job title.

Data Link - https://data.boston.gov/dataset/employee-earnings-report/resource/70129b87-bd4e-49bb-aa09-77644da73503

#### Crime Incident Report from Aug 2015 till date

Crime incident reports are provided by Boston Police Department (BPD). This Dataset contain data about crime occurred from 2015 till date and when and where that crime happened along with description about the incident.
Questions can be answered:

1.	Type of crimes in which district, location or area
2.	Which Day number of crimes happened frequently
3.	What time crime happened most/frequent.

Data Link - https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b

#### Boston property assessment 

Through this dataset we can analyses the Boston taxable and nontaxable property, Types of property.
Questions can be answered:

1.	Which property area have the highest gross tax?
2.	Which property have the largest area and which location? 
3.	Age of the property
3. Number of houses have been remodel?
4. Number of houses having 1 floor or more than 1 floor.

Data Link - https://data.boston.gov/dataset/property-assessment/resource/fd351943-c2c6-4630-992d-3f895360febd
