# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [113]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [114]:
### GRADED
# (a) Determine the shape, number of dimensions and type of elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
# (a) Determine the shape, number of dimensions and type of elements in the numpy array arr
# the shape
print("Shape of this array is: ", arr.shape)

# number of dimension
print("Number of dimension is: ", arr.ndim)

#type of elements
print("Array stores elements of type: ", arr.dtype)

# (b) Determine the sum of elements in arr
print("The sum of elements in this array is: ", arr.sum())

# (c) Determine the mean of elements in arr
print("The mean of elements in this array is: ", arr.mean())

# (d) Create an array of the same shape as arr but filled with zeros
print("An array is created with zeros and the same shape as arr: \n", np.zeros_like(arr))

# (e) Create an array of the same shape as arr but filled with ones
print("An array is created with ones and the same shape as arr: \n", np.ones_like(arr))

# (f) Create an array of the same shape as arr but where all elements are squared values
print("An array is created with squared values and the same shape as arr: \n", np.square(arr))

# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr)
arr1=arr # the original array with 3 rows and 5 columns
arr2=arr.T # transpose the original array, result of 5 rows and 3 columns
print("An array is created of shape 3*3 from array multiplication: \n", np.dot(arr1,arr2))

Shape of this array is:  (3, 5)
Number of dimension is:  2
Array stores elements of type:  int64
The sum of elements in this array is:  105
The mean of elements in this array is:  7.0
An array is created with zeros and the same shape as arr: 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
An array is created with ones and the same shape as arr: 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
An array is created with squared values and the same shape as arr: 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
An array is created of shape 3*3 from array multiplication: 
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [116]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [117]:
# (a) Determine the shape of the dataframe
print("The shape of the dataframe is: ", df.shape)

# (b) Print out all the columns of the dataframe
print("The names of all columns are: \n", list(df.columns))

# (c) Print the 3rd element of the dataframe
print("The 3rd element of the dataframe: \n", list(df.loc[2]))

# (d) Find the average of 'petal_width' where species is 'virginica'
vl_map1 = df.groupby('species')['petal_width'].mean() # use groupby to filter petal_width in terms of different species
result = vl_map['virginica'] # output the mean of 'virginica'
print("The average of petal_width in terms of virginica is: ", result)

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
vl_map2 = df.groupby('species')['sepal_width'].max() #use groupby to filter sepal_width in terms of different species
result = vl_map2['setosa']
print("The maximum of sepal_width in terms of setosa is: ", result)

# (f): What is the average value of sepal_length
vl_map3 = df.mean()
result = vl_map3['sepal_length'] 
print("The average value of sepal_length is: ", result)

# (g): What is the maximum value of sepal_width
vl_map4 = df.max()
result = vl_map4['sepal_width']
print("The maximum value of sepal_width is: ", result)

# (h): What is the minimum value of petal_width
vl_map5 = df.min()
result = vl_map5['petal_width']
print("The minimum value of petal_width is: ", result)

The shape of the dataframe is:  (150, 5)
The names of all columns are: 
 ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
The 3rd element of the dataframe: 
 [4.7, 3.2, 1.3, 0.2, 'setosa']
The average of petal_width in terms of virginica is:  2.026
The maximum of sepal_width in terms of setosa is:  4.4
The average value of sepal_length is:  5.843333333333334
The maximum value of sepal_width is:  4.4
The minimum value of petal_width is:  0.1


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


# List of Three Datasets:
## 1. Bicycle network within the city of Boston. 
The dataset of bicycle network within the city of Boston belongs to the Geospatial data, which is created by Boston's GIS department. This dataset contains more than 2,000 rows and 18 columns, including the object ID of bicylces, related street name, number of travel lanes and so on. To fully understand the infoamtion included in this dataset, three main questions will be asked:
(1). Which street has the most bicycles?
(2). What's the average travel lanes for bicycles in Boston?
(3). Which year install the most bicycles?
Dataset: https://www.data.gov/health/highlights

## 2. Hospital Charge.
The dataset includes hospital-specific charge for more than 3,000 US hospitals that receive Medicare Inpatient Prospective System (IPPS) payments for the top 100 most frequently billed discharges, paid under Medicare based on a rate per discharge using the Medicare Severity Diagnosis Related Group (DRG) for fiscal year 2011. It contains more than 16,000 DRGs, and includes average charges, average total payments and average Medicare payments (at the individual hospital level). To fully understand the infomation, I will make comparisons of the amount charged by individual hospitals within states.
Dataset: https://data.cms.gov/Medicare-Inpatient/Inpatient-Prospective-Payment-System-IPPS-Provider/97k6-zzx3

## 3. Product Recall.
This dataset summarizes and lists all the recalls of meat and poultry products produced by FSIS federally inspected establishments for the calendar year. Recalls are characterized by date, recall class, product, reason and pounds recalled. Due to the product recall was summarized in terms of each calendar year, I would like to compare from 2015-2017. All recalled products were classified into three classes, I would like to figure out which class has the most product recall in each year. Besides, what kind of problem will cause a product recall.
Dataset: https://www.data.gov/consumer/highlights