# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [4]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [54]:
### GRADED
arr = np.arange(15).reshape(3, 5)

# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print("shape: ", arr.shape)
print("type:  " , arr.dtype)
print("Dimension:  ", arr.ndim)

# (b) Determine the sum of elements in arr
print("sum of element in arr: ", np.sum([arr]))

# (c) Determine the mean of elements in arr
print("mean of element in arr: ", np.mean([arr]))

# (d) Create an array of the same shape as arr but filled with zeros
print("Array fill with zeros:  "'\n', np.zeros((3, 5)))

# (e) Create an array of the same shape as arr but filled with ones
print("Array fill with ones:  "'\n', np.ones((3, 5)))

# (f) Create an array of the same shape as arr but where all elements are squared values
print("Arr squared:  "'\n' , arr**2)

# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
print("New array 3 x 3:  "'\n', np.dot(arr, np.transpose(arr)))

shape:  (3, 5)
type:   int64
Dimension:   2
sum of element in arr:  105
mean of element in arr:  7.0
Array fill with zeros:  
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array fill with ones:  
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arr squared:  
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
New array 3 x 3:  
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [57]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(df.head(10)) #prints the first 10 rows

### GRADED
# (a) Determine the shape of the dataframe
print("Shape: ", df.shape)

# (b) Print out all the columns of the dataframe
column = list(df.head(0))
print("All columns of the dataframe:" ,'\n', column)

# (c) Print the 3rd element of the dataframe
Row = df.iloc[2,:]
Column = df.iloc[:,2]
print("the 3rd element of row:" , '\n', Row) 
print("the 3rd element of column:" , '\n', Column.head(2)) 

# (d) Find the average of 'petal_width' where species is 'virginica'
print("Mean of petal_width:" ,'\n', df[df['species']=='virginica']['petal_width'].mean())

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
print("Maximum sepal width:" ,'\n', df[df['species']=='setosa']['sepal_width'].max())

# (f): What is the average value of sepal_length
print("The average of Sepal length: ",'\n', df['sepal_length'].mean())

# (g): What is the maximum value of sepal_width
print("The maximum value of Sepal_max: ",'\n', df['sepal_width'].max())

# (h): What is the minimum value of petal_width
print("Minimum value of petal_width: ",'\n', df['petal_width'].min())


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
Shape:  (150, 5)
All columns of the dataframe: 
 ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
the 3rd element of row: 
 sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object
the 3rd e

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


1st (Bureau of Labor Statistics)
https://www.bls.gov/data/#employment
Datasets (1) :The database is about labor statistics from the United States Department of Labor. The database covers Employment, Productity, Price Index and Compensation.
Questions:
1. Which occupation and area are in the top 3 highest wage paying?
2. What is the labor force employment overview in the United States?
3. What occupation increase employment rate of the countries?

2nd (Marine Casualty Pollution Investigations)
https://homeport.uscg.mil/missions/investigations/marine-casualty-pollution-investigations
Datatset (2) :The Marine Casualty and Pollution Data files provide details about marine casualty and pollution incidents investigated by Coast Guard Offices throughout the United States. The database can be used to analyze marine accidents and pollution incidents by a variety of factors including vessel or facility type, injuries, fatalities, pollutant details, location, and date.  The data collection period began in 1982 for marine casualties and 1973 for polluting incidents, and is ongoing. Documentation includes entity and attribute descriptions along with suggested solutions to general marine pollution, vessel casualty, and personnel injury and death questions
Questions:
1. What is the U.S. Coast Guard Marine Casualty?
2. How to prevent from general marine pollution?
2. How to decrease personnel injury and death?

3rd (U.S. Government Education database)
https://catalog.data.gov/dataset?groups=education2168&_groups_limit=0
Datasets (3) : U.S. Government Education database is about education database across the United States. The database covers tuitions, national student loan, crime and safety, college scorecard and America Community Survey. I can use the College Scorecard to find out more about a college's affordability and value so they can make more informed decisions about which college to attend.
Questions:
1. Which college is famous among the United States?
2. Which state can provide the highest rate of national student loan?
3. Who are in the top 3 safety campus?
