# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [1]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [2]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
print(arr)
arr.shape
print('(a)The shape of this array is:', arr.shape,'.')
arr.ndim
print('(a)The number of dimension of this array is:', arr.ndim,'.')
type(arr)
print ('(a)The type of this array is:', type(arr),'.')
arr.sum()
print ('(b)The sum of elements in array is:', arr.sum(),'.')
arr.mean()
print ('(c)The mean of elements in array is:', arr.mean(),'.')
np.zeros_like(arr)
print('(d) an array of the same shape as arr but filled with zeros:',np.zeros_like(arr),)
np.ones_like(arr)
print ('(e) an array of the same shape as arr but filled with onesnp:',np.ones_like(arr),)
np.square(arr)
print ('(f)an array of the same shape as arr but where all elements are squared values:',np.square(arr),)
print(arr.T)
print('(g) an array result of shape 3*3 resulting from multiplication of arr with transpose',np.dot(arr,arr.T),)




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(a)The shape of this array is: (3, 5) .
(a)The number of dimension of this array is: 2 .
(a)The type of this array is: <class 'numpy.ndarray'> .
(b)The sum of elements in array is: 105 .
(c)The mean of elements in array is: 7.0 .
(d) an array of the same shape as arr but filled with zeros: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(e) an array of the same shape as arr but filled with onesnp: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(f)an array of the same shape as arr but where all elements are squared values: [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(g) an array result of shape 3*3 resulting from multiplication of arr with transpose [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [3]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows



sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [4]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [5]:
#(a) Determine the shape of the dataframe
df.shape
 

(150, 5)

In [6]:
# (b) Print out all the columns of the dataframe
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
# (c) Print the 3rd element of the dataframe
print (df.loc[2])

sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


In [22]:
# (d) Find the average of 'petal_width' where species is 'virginica'
df.groupby('species').mean().loc['virginica'].loc['petal_width']

2.026

In [23]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
df.groupby('species').max().loc['setosa'].loc['sepal_width']

4.4

In [26]:
# (f): What is the average value of sepal_length
df['sepal_length'].mean()

5.843333333333335

In [27]:
# (g): What is the maximum value of sepal_width
df['sepal_width'].max()

4.4

In [28]:
# (h): What is the minimum value of petal_width
df['petal_width'].min()

0.1

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


Lists of Three Interested Datasets:

1. FOOD ESTABLISHMENT INSPECTIONS
Since this is a legacy dataset containing records of city of Boston individual food safety inspections and results. I plan to produce plots and chart along with each year's food vendor's health inspections. Find their average trend and health condition.  
Link:https://data.boston.gov/dataset/food-establishment-inspections/resource/4582bec6-2b4f-4f9e-bc55-cbaa73117f4c


2.Fishery Commodities and Trade
This dataset contains value of imports and exports of fishery products from each countries. I will select top 10 fishery countries. to have comparision in these 10 countires from their data in 1976 to now. Link:http://www.fao.org/figis/servlet/TabSelector

3.Meals Programs in Seattle
This data set provides the names, locations, and service days of meal programs. I will find the max and min numbers of people for the meals program. as well as the average service day for meal program. create graphs from peak time. Link:https://catalog.data.gov/dataset/meals-programs-in-seattle-de35a