# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [5]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [20]:
### GRADED
arr = np.arange(15).reshape(3, 5)

# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print("shape: ", arr.shape)
print("type:  " , arr.dtype)
print("Dimension:  ", arr.ndim)


# (b) Determine the sum of elements in arr
print("sum of element in arr: ", np.sum([arr]))

# (c) Determine the mean of elements in arr
print("mean of element in arr: ", np.mean([arr]))

# (d) Create an array of the same shape as arr but filled with zeros
print("Array fill with zeros:  "'\n', np.zeros((3, 5)))

# (e) Create an array of the same shape as arr but filled with ones
print("Array fill with ones:  "'\n', np.ones((3, 5)))

# (f) Create an array of the same shape as arr but where all elements are squared values
print("Arr squared:  "'\n' , arr**2)






shape:  (3, 5)
type:   int64
Dimension:   2
sum of element in arr:  105
mean of element in arr:  7.0
Array fill with zeros:  
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array fill with ones:  
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arr squared:  
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


In [21]:
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dottr
tranpose = np.transpose(arr)
combi  = np.dot(arr, tranpose)

print("New array 3 x 3:  "'\n', combi)

New array 3 x 3:  
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [8]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print (df.head(10)) #prints the first 10 rows

### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
shape = df.shape
print("Shape:  ", shape)

# (b) Print out all the columns of the dataframe
Columns = df.columns
print(" All columns of dataframe:", Columns)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
Shape:   (150, 5)
 All columns of dataframe: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [9]:
# (c) Print the 3rd element of the dataframe
Row = df.iloc[3,:]
Column = df.iloc[:,3]
print("3rd element of row:  ", Row)

Top = Column.head(3)
print("3rd element of column: ", Top)


3rd element of row:   sepal_length       4.6
sepal_width        3.1
petal_length       1.5
petal_width        0.2
species         setosa
Name: 3, dtype: object
3rd element of column:  0    0.2
1    0.2
2    0.2
Name: petal_width, dtype: float64


In [10]:
# (d) Find the average of 'petal_width' where species is 'virginica'
virgin = df.groupby('species').mean().loc['virginica','petal_width']
print("Mean of petal_width:  ", virgin)


Mean of petal_width:   2.026


In [11]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
vir_max = df.groupby('species').max().loc['setosa', 'sepal_width']
print("Maximum sepal width:  ", vir_max)

Maximum sepal width:   4.4


In [12]:
# (f): What is the average value of sepal_length
Sepal_mean = df['sepal_length'].mean()
print("The average of Sepal length:  ", Sepal_mean)

The average of Sepal length:   5.843333333333335


In [14]:
# (g): What is the maximum value of sepal_width
Sepal_max = df['sepal_width'].max()
print('The maximum value of Sepal_max:  ', Sepal_max)


The maximum value of Sepal_max:   4.4


In [ ]:
# (h): What is the minimum value of petal_width

In [123]:
Sepal_min = df['petal_width'].min()
print("Minimum value of petal_width:  ", Sepal_min)

Minimum value of petal_width:   0.1


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)

###1st (Europe transport database)
### https://ec.europa.eu/eurostat/web/transport/overview
Datasets (1) : Europe transport database
    The database is about transportation database (train, airplanes, boats, trucks, cars) across europe. The database covers safety, infrastucture, equipment, traffic control, perfromance, and regional statistics. 
    I think this is good, because there are alot of information to be used in the reserachs.
    
Questions:
    1. Which transportation among the other has the highest safety rating?
    2. How to decrease traffic by using boats, train, bus, taxi.
    3. Which public transportation is more popular to public?
    4. Numbers of people and goods being transport.  
    
### 2nd (Boston: Property Assesment)
## hhttps://data.boston.gov/dataset/property-assessment/resource/fd351943-c2c6-4630-992d-3f895360febd

Datasets (2): Boston, Property Assesment
    The database is about property assesment in boston area. The database gives a preview of each property background.
    
Questions:
    1. Which property area have the largest total area (building & land) ?
    2. How many house was build in early 1980 and was bought after 2004.
    3. How many house have ore than 1 floor, and what is the average of house with 1 floor, 2 floor 3 floor?
    4. How many house have been remodel from scratch?
    
## 3rd (Agricultural: World agricultural data)
## Sources : http://statistics.amis-outlook.org/data/index.html

Datasets (3): Agricultural database
    The database shows agricultural database per year of specific country cover by AMIS. The databae covers production, domestic supply, domestic utilization, exports, imports, and closing stocks.
    
    Questions:
        1. Which agricultural performance has the highest between North America and Indonesia?
        2. What agriculture increase production rate of the countries?
        3. What product is famous among countries?
        4. Who are in the top 3 highest emport and export?

