# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [1]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [53]:
### GRADED
arr = np.arange(15).reshape(3, 5)
print(arr)
# (a) Determine the shape, number of dimensions and type of elements in the numpy array arr
print("(a).shape")
print(arr.shape)

print("number of dimensions")
print(arr.ndim)

print("type of elements in the numpy array arr")
print(arr.dtype)

# (b) Determine the sum of elements in arr
print("====="*10)
print("(b).The sum of elements")
print(arr.sum())

# (c) Determine the mean of elements in arr
print("====="*10)
print("(c).The mean of elements")
print(arr.mean())

# (d) Create an array of the same shape as arr but filled with zeros
print("====="*10)
print("(d).an array of the same shape as arr but filled with zeros")
array_zeros = np.zeros(arr.shape)
print(array_zeros)

# (e) Create an array of the same shape as arr but filled with ones
print("====="*10)
print("(e).an array of the same shape as arr but filled with ones")
array_ones = np.ones(arr.shape)
print(array_ones)

# (f) Create an array of the same shape as arr but where all elements are squared values
print("====="*10)
print("(f).an array of the same shape as arr but where all elements are squared values")
array_sq = np.square(arr)
print(array_sq)

# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
print("====="*10)
print("(g).an array result of shape 3*3")
arr_T = np.transpose(arr)
array1 = np.dot(arr,arr_T)
print(array1)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(a).shape
(3, 5)
number of dimensions
2
type of elements in the numpy array arr
int32
(b).The sum of elements
105
(c).The mean of elements
7.0
(d).an array of the same shape as arr but filled with zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(e).an array of the same shape as arr but filled with ones
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(f).an array of the same shape as arr but where all elements are squared values
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
(g).an array result of shape 3*3
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [59]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows
df_head10 = df.head(10)
print(df_head10)

# (a) Determine the shape of the dataframe
print("(a).shape")
df_shape = df.shape
print(df.shape)

# (b) Print out all the columns of the dataframe
print("====="*10)
print("(b).all the columns")
df_col = df.columns
print(df_col)

# (c) Print the 3rd element of the dataframe
print("====="*10)
print("(c).the 3rd element")
df_3elem = df.iloc[2]
print(df_3elem)

# (d) Find the average of 'petal_width' where species is 'virginica'
print("====="*10)
print("(d).the average of 'petal_width' where species is 'virginica'")
mean_pw = df[df["species"]=='virginica']['petal_width'].mean()
print(mean_pw)

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
print("====="*10)
print("(e).the maximum of 'sepal_width' where species is 'setosa'")
max_sw = df[df["species"]=='setosa']['sepal_width'].max()
print(max_sw)

# (f): What is the average value of sepal_length
print("====="*10)
print("(f).the average value of sepal_length")
avr_sl = df["sepal_length"].mean()
print(avr_sl)

# (g): What is the maximum value of sepal_width
print("====="*10)
print("(f).the maximum value of sepal_width")
max_sew = df["sepal_width"].max()
print(max_sew)

# (h): What is the minimum value of petal_width
print("====="*10)
print("(f).the minimum value of petal_width")
min_pw = df["petal_width"].min()
print(min_pw)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
(a).shape
(150, 5)
(b).all the columns
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
(c).the 3rd element
sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dty

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


# Dataset 1: Exchange Rates of US and UK

    Data Description:
    
    The data period is from January 1976 to November 2015 with a sum of 479 observations. The data period is from January 1976 to November 2015 with a sum of 479 observations. Data is collected from several institutions. British pound per dollar nominal exchange rates are obtained from the Federal Reserve Bank of St. Louis Economic Data(FRED). This study uses the United Kingdom as the domestic country, so exchange rates are defined as domestic prices per unit of the dollar, therefore, a rise in exchange rate indicates a depreciation of the British pound. Short-term interest rates for both countries are money market rates.
    
    Question that can be answered:
    Many literature suggests that exchanges rates are unable to predict since it follows a random walk. The random walk model is as follows: 𝑒t = 𝑒t+1 + 𝜈t. Therefore, I use this dataset to forecast the random walk model. By the definition of the random walk without drift, exchange rates follow a martingale difference process, in other words, E(et+1|et, et-1, …, e0) = et for all t; the best prediction of et+1 is et for all t >= 0. 
    

        

# Dataset 2: Interest Rates of US and UK, Exchange Rates of US and UK

Data Description: 

Monthly variables. The data period is from January 1976 to November 2015 with a sum of 479 observations. Interest rates for the UK are downloaded from International Financial Statistics of the International Monetary Fund (IMF). Following Ince, Molodtsova and Papell (2015), for the U.S., interest rates before 2008 are federal fund rates(FFRs), and that after 2008 are replaced by Wu-Xia’s shadow FFRs.

Questions that can be answered: 

Combine with dataset 1, test the uncovered interest rate parity (UIRP) which suggests that the interest rate differential is equal to the exchange rate differential.


# Dataset 3: Consumer Price Index (CPI) of UK and US

Data Description:

Monthly variables. The data period is from January 1976 to November 2015 with a sum of 479 observations. Consumer Price Index (CPI) is used to represent price levels.

Question that can be answered:

Using Purchasing Power Parity (PPP) fundamentals to forecast exchange rate. PPP suggests that the real prices of a basket of goods between two countries are the same, i.e. when converting domestic currency to foreign currency at the PPP rate, the same baskets of goods can be bought, which indicates the same price level.