# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [5]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [6]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

# (a) Determine the shape, number of dimensions and type of elements in the numpy array arr
import pandas as pd
import numpy as np
print('The shape of arr is:',arr.shape)
print('The type of arr is:',type(arr))
print('The dimensions of arr is:',arr.ndim)

# (b) Determine the sum of elements in arr
print('The sum of elements in arr is:',arr.sum())

# (c) Determine the mean of elements in arr
print('The mean of elements in arr is:',arr.mean())

# (d) Create an array of the same shape as arr but filled with zeros
d=np.zeros_like(arr)
print('The same shape but filled with zeros',d)

# (e) Create an array of the same shape as arr but filled with ones
e=np.ones((3,5))
print('The same shape but filled with ones:',e)

# (f) Create an array of the same shape as arr but where all elements are squared values
f=arr**2
print('The same shape but where all elements are squared values:')
print(f)

# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
g=arr.dot(arr.T)
print('The new array:')
print(g)


The shape of arr is: (3, 5)
The type of arr is: <class 'numpy.ndarray'>
The dimensions of arr is: 2
The sum of elements in arr is: 105
The mean of elements in arr is: 7.0
The same shape but filled with zeros [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
The same shape but filled with ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
The same shape but where all elements are squared values:
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
The new array:
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [7]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

# (a) Determine the shape of the dataframe
print('The shape of the dataframe:',df.shape)
print('----------------')

# (b) Print out all the columns of the dataframe
print(df)
print('================')
# (c) Print the 3rd element of the dataframe
c=df.ix[[2],:]
print('c',c)
print('================')

# (d) Find the average of 'petal_width' where species is 'virginica'
d=df.groupby('species').mean()
print('d',d)
print('================')

# (e) Find the maximum of 'sepal_width' where species is 'setosa'
e=df.groupby('species').max()
print('e',e)
print('================')

# (f): What is the average value of sepal_length
f=df.ix[:,[0]]
f1=f.mean()
print('The average of sepal_length:',f1)

# (g): What is the maximum value of sepal_width
g=df.ix[:,[1]]
g1=g.max()
print('The maximum value of sepal_width:',g1)

# (h): What is the minimum value of petal_width
h=df.ix[:,[3]]
h1=h.min()
print("The minimum value of petal_width:",h1)


The shape of the dataframe: (150, 5)
----------------
     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4     

C:\Users\Jack_\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Jack_\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Jack_\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Jack_\Anaconda3\lib\site-packages\ipykernel_launcher.py:48: DeprecationWarning: 
.ix is deprecated. Please

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


In [2]:
import pandas as pd
import numpy as np
df1=pd.read_csv('crime_incident_reports.csv')
df1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182091459          3301                  Verbal Disputes   
1           I182091456          3801  Motor Vehicle Accident Response   
2           I182091454          2647                            Other   
3           I182091451          3115               Investigate Person   
4           I182091450          3006               Medical Assistance   
5           I182091447          3831  Motor Vehicle Accident Response   
6           I182091446          3410                            Towed   
7           I182091445          3802  Motor Vehicle Accident Response   
8           I182091442           613                          Larceny   
9           I182091440          2905                       Violations   
10          I182091437          1842                   Drug Violation   
11          I182091436          3301                  Verbal Disputes   
12          I182091434           619                          Larceny   
13          I182091433          3831  Motor Vehicle Accident Response   
14          I182091432           802                   Simple Assault   
15          I182091431           802                   Simple Assault   
16          I182091428          2647                            Other   
17          I182091428           619                          Larceny   
18          I182091425           619                          Larceny   
19          I182091424           801                   Simple Assault   
20          I182091424          2101    Operating Under the Influence   
21          I182091424           802                   Simple Assault   
22          I182091424          2405               Disorderly Conduct   
23          I182091424          3802  Motor Vehicle Accident Response   
24          I182091424          3831  Motor Vehicle Accident Response   
25          I182091424           413               Aggravated Assault   
26          I182091423          3112         Landlord/Tenant Disputes   
27          I182091421          3115               Investigate Person   
28          I182091420          3201                    Property Lost   
29          I182091419          3114             Investigate Property   
...                ...           ...                              ...   
338823   I110177502-00           802                   Simple Assault   
338824   I110177502-00           802                   Simple Assault   
338825   I100636670-00          3125                  Warrant Arrests   
338826   I100636670-00           629                          Larceny   
338827   I100636670-00           629                          Larceny   
338828   I100340225-00           339                          Robbery   
338829   I100340225-00           339                          Robbery   
338830   I100340225-00           339                          Robbery   
338831   I100340225-00           339                          Robbery   
338832   I100340225-00          3125                  Warrant Arrests   
338833   I100222105-02          3125                  Warrant Arrests   
338834   I100033064-00          2907                       Violations   
338835   I100033064-00          2910                       Violations   
338836   I100033064-00          2910                       Violations   
338837   I090321958-00          3125                  Warrant Arrests   
338838   I090321958-00          3125                  Warrant Arrests   
338839   I090317057-00          3125                  Warrant Arrests   
338840   I090317057-00           403               Aggravated Assault   
338841   I080542626-00          1849                   Drug Violation   
338842   I080542626-00          1848                   Drug Violation   
338843   I080542626-00          1848                   Drug Violation   
338844   I080542626-00          3125                  Warrant Arrests   
338845   I060168073-00          1864                   Drug Viola

In [3]:
Example1=df1.loc[(df1['DAY_OF_WEEK']=='Sunday')]
Example1

INCIDENT_NUMBER  OFFENSE_CODE                OFFENSE_CODE_GROUP  \
0           I182091459          3301                   Verbal Disputes   
1           I182091456          3801   Motor Vehicle Accident Response   
3           I182091451          3115                Investigate Person   
4           I182091450          3006                Medical Assistance   
5           I182091447          3831   Motor Vehicle Accident Response   
6           I182091446          3410                             Towed   
7           I182091445          3802   Motor Vehicle Accident Response   
8           I182091442           613                           Larceny   
9           I182091440          2905                        Violations   
10          I182091437          1842                    Drug Violation   
11          I182091436          3301                   Verbal Disputes   
12          I182091434           619                           Larceny   
14          I182091432           802                    Simple Assault   
15          I182091431           802                    Simple Assault   
16          I182091428          2647                             Other   
17          I182091428           619                           Larceny   
18          I182091425           619                           Larceny   
19          I182091424           801                    Simple Assault   
20          I182091424          2101     Operating Under the Influence   
21          I182091424           802                    Simple Assault   
22          I182091424          2405                Disorderly Conduct   
23          I182091424          3802   Motor Vehicle Accident Response   
24          I182091424          3831   Motor Vehicle Accident Response   
25          I182091424           413                Aggravated Assault   
26          I182091423          3112          Landlord/Tenant Disputes   
27          I182091421          3115                Investigate Person   
29          I182091419          3114              Investigate Property   
31          I182091415          3831   Motor Vehicle Accident Response   
32          I182091412          2660                             Other   
33          I182091412          1810                    Drug Violation   
...                ...           ...                               ...   
336886      I152051278           616                           Larceny   
336887      I152051274           522              Residential Burglary   
336888      I152051273           522              Residential Burglary   
336889      I152051272          3301                   Verbal Disputes   
336890      I152051271          3802   Motor Vehicle Accident Response   
336892      I152051268          3304  Assembly or Gathering Violations   
336893      I152051268          2204                  Liquor Violation   
336894      I152051266           802                    Simple Assault   
336895      I152051264          2636        Prisoner Related Incidents   
336896      I152051264          2905                        Violations   
336897      I152051263           423                Aggravated Assault   
336900      I152051258          3111                 License Violation   
338349   I152039327-00           633                           Larceny   
338350   I152039327-00           633                           Larceny   
338351   I152039327-00          3125                   Warrant Arrests   
338352   I152039327-00           361                           Robbery   
338411   I152010121-00           770                        Auto Theft   
338412   I152010121-00           770                        Auto Theft   
338413   I152010121-00          3125                   Warrant Arrests   
338505   I142036405-00          2623                             Other   
338628   I140188130-00          3125                   Warrant Arrests   
338640   I140110321-00          3125                   Warrant Arrests   
338641   I1

In [4]:
Example2=df1.loc[(df1['UCR_PART']=='Part Two')]
Example2

INCIDENT_NUMBER  OFFENSE_CODE             OFFENSE_CODE_GROUP  \
2           I182091454          2647                          Other   
9           I182091440          2905                     Violations   
10          I182091437          1842                 Drug Violation   
14          I182091432           802                 Simple Assault   
15          I182091431           802                 Simple Assault   
16          I182091428          2647                          Other   
19          I182091424           801                 Simple Assault   
20          I182091424          2101  Operating Under the Influence   
21          I182091424           802                 Simple Assault   
22          I182091424          2405             Disorderly Conduct   
32          I182091412          2660                          Other   
33          I182091412          1810                 Drug Violation   
34          I182091412           802                 Simple Assault   
35          I182091412          1849                 Drug Violation   
36          I182091412          1848                 Drug Violation   
40          I182091403          2403             Disorderly Conduct   
43          I182091400          2662                     Ballistics   
55          I182091386          2628          Phone Call Complaints   
61          I182091380          2647                          Other   
67          I182091375          2905                     Violations   
69          I182091373          2907                     Violations   
71          I182091370          1402                      Vandalism   
82          I182091353          1402                      Vandalism   
93          I182091337          1402                      Vandalism   
94          I182091336          2629                     Harassment   
100         I182091329          2647                          Other   
105         I182091319          1001                 Counterfeiting   
111         I182091310          2629                     Harassment   
118         I182091302          1402                      Vandalism   
119         I182091301          1402                      Vandalism   
...                ...           ...                            ...   
338718   I130325877-00          2632                   Evading Fare   
338719   I130325877-00          2632                   Evading Fare   
338750   I130084703-00           802                 Simple Assault   
338764   I130031413-00          1866                 Drug Violation   
338765   I130031413-00          1874                 Drug Violation   
338766   I130031413-00          1846                 Drug Violation   
338767   I130031413-00          1874                 Drug Violation   
338769   I130007264-01          1001                 Counterfeiting   
338770   I120720047-00          1503             Firearm Violations   
338789   I120283195-00          2647                          Other   
338796   I120201612-00          1841                 Drug Violation   
338797   I120201612-00          1841                 Drug Violation   
338798   I120201612-00          1841                 Drug Violation   
338800   I120189428-00           802                 Simple Assault   
338801   I120189428-00           802                 Simple Assault   
338802   I120189428-00           802                 Simple Assault   
338804   I120069826-00          2610                          Other   
338805   I120069826-00          2610                          Other   
338806   I110694557-00          1605                   Prostitution   
338807   I110694557-00          1605                   Prostitution   
338823   I110177502-00           802                 Simple Assault   
338824   I110177502-00           802                 Simple Assault   
338834   I100033064-00          2907                     Violations   
338835   I100033064-00          2910                     Violations   
338836   I100033064-00         

This crime_incident_reports has 338853 rows and 17 columns. Based on the data showed by this file, we are able to see the detailed time, the area, the code and other information of criminal events.
What's more, if you want to learn the details of some criminal events, such as type, area, street, you can use some formulas to extract specific rows or columns, such as df.loc[], df.ix[] Furthermore, if you want to research the rate of occuring the shooting events, you can select and type those statistics which basic condition is the shooting type. Then, you are able to analyze which places have more possibility to have such events and predict the possibility of occuring next similiar event, such as the table of Example1 which enables you to analyze some criminal events of Sunday. Moreover, as you can see, the final column is about the location. With this kind of information, it enables researchers to go to the real place to analyze the events, which can help researchers to find out the real reasons,such as the table of Example2.
The questions can be answered include: 
1) The comparison of criminal possibility between Sunday and Saturday;
2) Which street has the most possibility of occurring criminal events?
3) Which area has the most possibility of occurrin criminal events?
4) Which year has the most possibility of occurring criminal events?
5) In the same year, which month has the most criminal events?
6) Which offensive code is used the most?
7) Describe the relationship between Area and Hour?
8) How long is the longest time in the same area?

In [5]:
df2=pd.read_csv('employee-earnings-report-2017.csv')
df2

NAME                DEPARTMENT NAME  \
0              Miller,Francis T       Boston Police Department   
1       Sullivan,Patrice Murphy       Boston Police Department   
2              O'Hara,Michael C       Boston Police Department   
3              Whalen,Richard L       Boston Police Department   
4               Kelly,Ann Marie       Boston Police Department   
5             Carroll,William F       Boston Police Department   
6               Connolly,John J       Boston Police Department   
7                  Ivens,Paul M       Boston Police Department   
8                  Kelly,John R       Boston Police Department   
9               Klokman,John A.       Boston Police Department   
10                Newton,Robert       Boston Police Department   
11          Peters,Kenneth A Jr       Boston Police Department   
12           Rodriguez,Carmen N       Boston Police Department   
13             Hartgrove,Todd M       Boston Police Department   
14            Younger,Vatchel S       Boston Police Department   
15      Hartgrove,Christopher A       Boston Police Department   
16                 Lee,George Y       Boston Police Department   
17               Turner,Keith A       Boston Police Department   
18              Carnell,James W       Boston Police Department   
19            Crossen,Patrick J       Boston Police Department   
20              Meade,Stephen M       Boston Police Department   
21           Chinetti,William J       Boston Police Department   
22               McGill,Kevin J       Boston Police Department   
23              Canney,Joseph H       Boston Police Department   
24              Fish,Michael A.       Boston Police Department   
25              Terenzi,Phillip       Boston Police Department   
26           Spellman,Deborah M       Boston Police Department   
27                 Flynn,Anna E       Boston Police Department   
28          Buchanan,Basil Mark       Boston Police Department   
29          Caulfield,Richard P       Boston Police Department   
...                         ...                            ...   
22215            Barros,Eurides         Fam & Student Engagemt   
22216         Ahmed,Said Hassan    BPS South Boston HS - Excel   
22217             Assiraj,Farah              Newcomers Academy   
22218             OGarro,De'Lea    BPS South Boston HS - Excel   
22219         Inciarte,Himilcon                      Tobin K-8   
22220     Rivera,Maria Victoria                  Green Academy   
22221                Gary,Grant        BPS Chittick Elementary   
22222   Harewood,Alexis Octavia     Kennedy, EM Health Academy   
22223            Owens,Joy Wong           Henderson Elementary   
22224       Gomez,Curtis Joseph          BPS Special Education   
22225       Lake,Kimberly Marie          UP Academy Dorchester   
22226           Mansfield,Laura                 BPS Burke High   
22227  Rowlinson,Veronica Ramos           BPS East Boston High   
22228              Demaidi,Sara            Young Achievers K-8   
22229            Gonzalez,Julia      BPS Office Of Budget Mgmt   
22230               Rok,Kaitlin          BPS Holmes Elementary   
22231       Gilson,Brittany Ann           BPS Tynan Elementary   
22232            Vanegas,Monica                      Tobin K-8   
22233      Poindexter,Nicolette   BPS Substitute Teachers/Nurs   
22234          Rodrigues,Anjali        BPS Boston Arts Academy   
22235          Sterrer,Marina R       BPS Higginson Elementary   
22236            West,Kelcy Lyn                       Lyon K-8   
22237                Berman,Ann        BPS Chittick Elementary   
22238            Simoes,Julie A  BPS Orchard Gardens K-8 Pilot   
22239  Walkenstein,Emily Rebeca             Mildred Avenue K-8   
22240         Flaherty,Thomas C       Boston Police Department   
22241              Simon,Victor               Parks Department   
22242              Lara,Diana D                     Edison K-8   
22243     Gross,William Brenden       Boston Police Department   
2

According to the table, we area able to know the information of name, position, department name, the regular salary and other data, which enables us to research the relationship of position, district and salary.
As you can see, this table provides us with detailed statistics. With those data, you can know the salary of some position, the working time and their departments. By analyzing these information, it enables readers to realize the level of each role and help them build the goals. 
The questions can be answered include:
1) Which job title can get the highest salary?
2) Which department has the highest salary?
3) Based on the same job title, which department gives the highest salary?
4) Which job title has the highest overtime salary?
5) Who will get the highest salary? Which department he works for?
6) Which department has the most employees?
7) Which postal is the most?

In [3]:
df3=pd.read_csv('cwurData.csv')
df3

world_rank                                        institution  \
0              1                                 Harvard University   
1              2              Massachusetts Institute of Technology   
2              3                                Stanford University   
3              4                            University of Cambridge   
4              5                 California Institute of Technology   
5              6                               Princeton University   
6              7                               University of Oxford   
7              8                                    Yale University   
8              9                                Columbia University   
9             10                 University of California, Berkeley   
10            11                              University of Chicago   
11            12                                 Cornell University   
12            13                         University of Pennsylvania   
13            14                                University of Tokyo   
14            15                           Johns Hopkins University   
15            16    Swiss Federal Institute of Technology in Zurich   
16            17                                   Kyoto University   
17            18                      Weizmann Institute of Science   
18            19              University of California, Los Angeles   
19            20                University of California, San Diego   
20            21                             Rockefeller University   
21            22                     Hebrew University of Jerusalem   
22            23                                New York University   
23            24            University of California, San Francisco   
24            25                    University of Wisconsin–Madison   
25            26         University of Illinois at Urbana–Champaign   
26            27                                    Duke University   
27            28                            Imperial College London   
28            29    University of Texas Southwestern Medical Center   
29            30                      University of Texas at Austin   
...          ...                                                ...   
2170         971                         Fu Jen Catholic University   
2171         972                            Hunan Normal University   
2172         973  Ulsan National Institute of Science and Techno...   
2173         974                  Federal University of Santa Maria   
2174         975                                Shenzhen University   
2175         976                         Tianjin Medical University   
2176         977                   Beijing University of Technology   
2177         978              University of Reims Champagne-Ardenne   
2178         979                                 Yuan Ze University   
2179         980     University of Chemistry and Technology, Prague   
2180         981                             University of Limerick   
2181         982                     China Medical University (PRC)   
2182         983                               Feng Chia University   
2183         984                  Zhejiang University of Technology   
2184         985                       Novosibirsk State University   
2185         986                            University of Bucharest   
2186         987                            Babeș-Bolyai University   
2187         988                                Mansoura University   
2188         989              University of Pau and Pays de l'Adour   
2189         990                            Henan Normal University   
2190         991                                  Xidian University   
2191         992                        Federal University of Bahia   
2192         993                      Southwest Jiaotong University   
2193         994                                 Ryerson University   
2194         995              

This csv file provides a table with universities, its countries, its rank, the quality of education, and other things.
According to those statistics, it not only helps education institutions access and arrange the rank of top 100 universities but also gives the readers to learn and provides the instructions of selecting universities. What's more, this kind of statistics also provides some universities with some suggestions that why some universities of top 30 have such higher quality education. According to the analysis, those universities of lower levels can realize how to increase their competitiveness and make progress.
The questions can be answered include:
1) Which university has the highest quality of education?
2) Which university has the most alumnus?
3) Which university has the highest quality of faculty?
4) Which university has the biggest influence?
5) Which university has the most patents?
6) Which university has the highest score?
7) How many universities are built in 2012?