# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [4]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
print(arr.shape)
print(arr.ndim)
print(type(arr))

(3, 5)
2
<class 'numpy.ndarray'>


In [14]:
# (b) Determine the sum of elements in arr
arr.sum(axis=0)
arr.sum(axis=1)
arr.sum()

105

In [15]:
# (c) Determine the mean of elements in arr
arr.mean()

7.0

In [5]:
# (d) Create an array of the same shape as arr but filled with zeros
d = np.zeros_like(arr)
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
# (e) Create an array of the same shape as arr but filled with ones
e = np.ones_like(arr)
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
# (f) Create an array of the same shape as arr but where all elements are squared values
f = np.square(arr)
f

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [8]:
#(g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
g = arr.dot(arr.T). reshape(3,3)
g

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [10]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [24]:
# (a) Determine the shape of the dataframe
df.shape

(150, 5)

In [11]:
# (b) Print out all the columns of the dataframe
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [12]:
# (c) Print the 3rd element of the dataframe
print(df.iloc[2])

sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


In [15]:
# (d) Find the average of 'petal_width' where species is 'virginica'
df['petal_width'].groupby(df['species'] == 'virginica').mean()

species
False    0.786
True     2.026
Name: petal_width, dtype: float64

In [17]:
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
df['sepal_width'].groupby(df['species'] == 'setosa').max()

species
False    3.8
True     4.4
Name: sepal_width, dtype: float64

In [18]:
# (f): What is the average value of sepal_length
df['sepal_length'].mean()

5.843333333333335

In [31]:
# (g): What is the maximum value of sepal_width
df['sepal_width'].max()

4.4

In [32]:
# (h): What is the minimum value of petal_width
df['petal_width'].min()

0.1

### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


# Q1

1. Cityscore: https://data.boston.gov/dataset/cityscore
2. Employment: https://www.bls.gov/bls/proghome.htm#employment
3. U.S. Hourly Precipitation Data: https://catalog.data.gov/dataset/u-s-hourly-precipitation-data

# Q2